# -*- coding: utf-8 -*-
"""iris_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fauxp5rVWtBXEgbYh7_tZsZcFTof7rJk
"""

"""
IRIS SPECIES CLASSIFICATION PROJECT
Main script: project.py

- Loads Iris.csv
- Performs basic EDA
- Trains and compares 3 models
- Prints metrics and shows plots
"""

import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
)
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier


# -------------------------------------------------------------------
# 1. Data loading
# -------------------------------------------------------------------
def load_data(csv_path: str) -> pd.DataFrame:
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"File not found: {csv_path}")

    df = pd.read_csv(csv_path)

    # Remove Id column if present
    if "Id" in df.columns:
        df = df.drop(columns=["Id"])

    return df


# -------------------------------------------------------------------
# 2. Exploratory Data Analysis (EDA)
# -------------------------------------------------------------------
def run_eda(df: pd.DataFrame) -> None:
    print("\n=== DATA INFO ===")
    print(df.info())

    print("\n=== FIRST 5 ROWS ===")
    print(df.head())

    print("\n=== STATISTICAL SUMMARY ===")
    print(df.describe())

    # Species distribution
    plt.figure(figsize=(6, 4))
    sns.countplot(x="Species", data=df)
    plt.title("Species Distribution")
    plt.tight_layout()
    plt.show()

    # Pairplot by species
    sns.pairplot(df, hue="Species")
    plt.suptitle("Pairplot of Iris Features by Species", y=1.02)
    plt.show()

    # Correlation heatmap (numeric only)
    numeric_df = df.drop(columns=["Species"])
    corr = numeric_df.corr()

    plt.figure(figsize=(6, 4))
    sns.heatmap(corr, annot=True, cmap="Blues", fmt=".2f")
    plt.title("Correlation Heatmap — Iris Features")
    plt.tight_layout()
    plt.show()


# -------------------------------------------------------------------
# 3. Data preparation
# -------------------------------------------------------------------
def prepare_data(df: pd.DataFrame):
    X = df.drop(columns=["Species"])
    y = df["Species"]

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.25,
        random_state=42,
        stratify=y
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    return X_train, X_test, X_train_scaled, X_test_scaled, y_train, y_test


# -------------------------------------------------------------------
# 4. Train and evaluate multiple models
# -------------------------------------------------------------------
def train_and_evaluate_models(
    X_train, X_test, X_train_scaled, X_test_scaled, y_train, y_test
):
    models = {
        "Logistic Regression": LogisticRegression(max_iter=300),
        "KNN": KNeighborsClassifier(),
        "Decision Tree": DecisionTreeClassifier(random_state=42),
    }

    results = []

    for name, model in models.items():
        # Tree doesn't require scaling; others will use scaled features
        if name == "Decision Tree":
            model.fit(X_train, y_train)
            preds = model.predict(X_test)
        else:
            model.fit(X_train_scaled, y_train)
            preds = model.predict(X_test_scaled)

        acc = accuracy_score(y_test, preds)
        results.append((name, acc, preds))

        print("\n" + "=" * 50)
        print(f"MODEL: {name}")
        print(f"Accuracy: {acc:.4f}")
        print("\nClassification Report:")
        print(classification_report(y_test, preds))

    # Choose best model by accuracy
    best_model_name, best_acc, best_preds = max(results, key=lambda x: x[1])
    print("\n" + "=" * 50)
    print(f"BEST MODEL: {best_model_name} (Accuracy = {best_acc:.4f})")

    return best_model_name, best_acc, best_preds, models


# -------------------------------------------------------------------
# 5. Confusion matrix plotting
# -------------------------------------------------------------------
def plot_confusion(y_true, y_pred, title: str) -> None:
    cm = confusion_matrix(y_true, y_pred)
    labels = np.unique(y_true)

    plt.figure(figsize=(5, 4))
    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=labels,
        yticklabels=labels,
    )
    plt.title(f"Confusion Matrix — {title}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.tight_layout()
    plt.show()


# -------------------------------------------------------------------
# Main execution
# -------------------------------------------------------------------
def main():
    csv_path = "Iris.csv"

    print("=== IRIS CLASSIFICATION PROJECT ===")

    # 1. Load data
    df = load_data(csv_path)

    # 2. EDA
    run_eda(df)

    # 3. Prepare data
    X_train, X_test, X_train_scaled, X_test_scaled, y_train, y_test = prepare_data(df)

    # 4. Train & compare models
    best_model_name, best_acc, best_preds, models = train_and_evaluate_models(
        X_train, X_test, X_train_scaled, X_test_scaled, y_train, y_test
    )

    # 5. Plot confusion matrix for best model
    plot_confusion(y_test, best_preds, best_model_name)

    print("\nProject finished successfully.")


if __name__ == "__main__":
    main()